name:                expose-me
version:             0.1.0.0
github:              "githubuser/expose-me"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/expose-me#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- websockets
- bytestring
- text
- http-types
- aeson
- optparse-applicative
- yaml
- wai-websockets
- binary
- either
- hashtables
- hashable
- stm

default-extensions:
- OverloadedStrings
- LambdaCase
- BlockArguments
- FlexibleContexts
- TemplateHaskell
- ScopedTypeVariables
- BangPatterns
- RankNTypes
- MagicHash
- DeriveGeneric

library:
  source-dirs: src

executables:
  tserver:
    main:                Main.hs
    source-dirs:         app-tserver
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expose-me
  tclient:
    main:                Main.hs
    source-dirs:         app-tclient
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expose-me

tests:
  expose-me-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - expose-me
