name:                tunnelme
version:             0.1.0.0
github:              "losfair/tunnelme"
license:             BSD3
author:              "Heyang Zhou"
maintainer:          "zhy20000919@hotmail.com"
copyright:           "2021 Heyang Zhou"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/losfair/tunnelme#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- websockets
- bytestring
- text
- http-types
- aeson
- optparse-applicative
- yaml
- wai-websockets
- binary
- either
- hashtables
- hashable
- stm
- cryptonite
- base16-bytestring >= 1
- wuss
- network

default-extensions:
- OverloadedStrings
- LambdaCase
- BlockArguments
- FlexibleContexts
- TemplateHaskell
- ScopedTypeVariables
- BangPatterns
- RankNTypes
- MagicHash
- DeriveGeneric

library:
  source-dirs: src

executables:
  tserver:
    main:                Main.hs
    source-dirs:         app-tserver
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tunnelme
  tclient:
    main:                Main.hs
    source-dirs:         app-tclient
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tunnelme
  topen:
    main:                Main.hs
    source-dirs:         app-topen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tunnelme

tests:
  tunnelme-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tunnelme
